week 3 assessment
learn-academy-2022-hotel/week-3-assessment-mollykwolf pull request #1
Opened 2023-01-03 17:20 UTC by mollykwolf

# Submitting Week 3 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ x] Coding Challenges
- [ x] Interview Questions
- [ ] React Debugging

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here: The last coding challenge question I was having trouble writing a code that would return the desired result.

2023-01-04 01:16 UTC, nmaresrivera11 requested changes
I left some pseudo code to help you try again on question #3 in the coding challenges. If you need some more help with this question, let me know and we can meet one on one so I can help explain this a little better.

2023-01-04 01:16 UTC, TsunamiCode5 commented on code-challenges.test.js
> +
I am going to provide you with some pseudocode that you can use to try and attempt this question again. If you still need some help just let me know and we can meet one on one to further get into some solutions we could use.
Pseudocode:
- First we will use the naming conventions you used (accumlatingSum)
- The parameter it will receive will be (array)
- Inside of my accumlatingSum function I will declare a couple variables to hold a value of zero and an empty array
- There are different avenues to venture but we need to use iteration to go through our array (for loop / map)
- From here we want to add and push the new value into the empty array

2023-01-05 02:25 UTC, mollykwolf commented
Hey Nicole, thanks for your help! I am still working through the third challenge. Once it's completed, do I push my  updated branch up to gitHub and create a new PR? Or how to update my code on gitHub?

2023-01-05 19:33 UTC, nmaresrivera11 commented on code-challenges.test.js
> +//     fibonacciArray.push(nextNumber) // on first run makes array [1, 1, 2]
Great note taking!

2023-01-05 19:34 UTC, nmaresrivera11 commented on code-challenges.test.js
> +// //     const fibLength1 = 6
Nice job hoisting your variables inside of your tests, it is a really good practice!

2023-01-05 19:35 UTC, nmaresrivera11 commented on code-challenges.test.js
> +//   arrayOfValues = Object.values(object)
Great job!

2023-01-05 19:47 UTC, nmaresrivera11 approved these changes
Molly, you are doing so well! I am glad to hear that things are starting to click. You code looks great and after our discussion I would like to see next week assessment pseudo code reflect your ideas, some vocab, and your brainstorming. Your interview answers were really good and you were using the researched answers section to go a bit more in depth about the concept which is amazing. This assessment comprehension level is at a Novice but let's see that pseudo code have a bit more detail next week to get us to advanced beginner level. Great work, Molly!

2023-01-06 00:51 UTC, merged